api_hash: cdc8cdd44652aa71e29ce5a5026a1d7d
api_id: 27627899
chat_id: -1001234897244
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
